notifications:
  email: false
sudo: false
language: java
dist: bionic
jdk:
  - oraclejdk11
cache:
  directories:
    - $HOME/.m2
install: true
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -DskipITs -Dmaven.javadoc.skip=true org.jacoco:jacoco-maven-plugin:report coveralls:report -B -V
