notifications:
  email: false
sudo: false
language: java
dist: bionic
jdk:
  - oraclejdk11
cache:
  directories:
    - $HOME/.m2
install: true
script:
  - mvn clean install -DskipITs -Dmaven.javadoc.skip=true -B -V
