version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: clio-postgres
    environment:
      - POSTGRES_DB=clio_local
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
  clio-reporting-local:
    image: europeana/clio-reporting:develop
    container_name: clio-reporting-local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      HIBERNATE_CONNECTION_URL: jdbc:postgresql://clio-postgres:5432/metis-clio_local
    volumes:
      - /data/metis-configuration/clio/clio-reporting/clio-reporting-rest/k8s/overlays/local/components/properties/application.properties:/application.properties
      - /data/metis-configuration/k8s/common-components/custom-truststore-jks/custom-truststore.jks:/data/certificates/custom-truststore.jks
      - /data/metis-configuration/k8s/common-components/log4j2-xml/log4j2.xml:/data/logging/log4j2.xml
    depends_on:
      - postgres
